{"id":"../../node_modules/axios/lib/cancel/CanceledError.js","dependencies":[{"name":"C:\\Users\\login\\Desktop\\4-natours\\package.json","includedInParent":true,"mtime":1745304383819},{"name":"C:\\Users\\login\\Desktop\\4-natours\\node_modules\\axios\\package.json","includedInParent":true,"mtime":1745212461738},{"name":"../core/AxiosError","loc":{"line":3,"column":25,"index":40},"parent":"C:\\Users\\login\\Desktop\\4-natours\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"C:\\Users\\login\\Desktop\\4-natours\\node_modules\\axios\\lib\\core\\AxiosError.js"},{"name":"../utils","loc":{"line":4,"column":20,"index":83},"parent":"C:\\Users\\login\\Desktop\\4-natours\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"C:\\Users\\login\\Desktop\\4-natours\\node_modules\\axios\\lib\\utils.js"}],"generated":{"js":"'use strict';\n\nvar AxiosError = require('../core/AxiosError');\nvar utils = require('../utils');\n\n/**\n * A `CanceledError` is an object that is thrown when an operation is canceled.\n *\n * @class\n * @param {string=} message The message.\n * @param {Object=} config The config.\n * @param {Object=} request The request.\n */\nfunction CanceledError(message, config, request) {\n  // eslint-disable-next-line no-eq-null,eqeqeq\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED, config, request);\n  this.name = 'CanceledError';\n}\n\nutils.inherits(CanceledError, AxiosError, {\n  __CANCEL__: true\n});\n\nmodule.exports = CanceledError;\n"},"sourceMaps":null,"error":null,"hash":"df711eb0e3de6f92d85ad2c3978e0f48","cacheData":{"env":{}}}